 <?php

 $title = 'Add new employee';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('application', array('action' => 'add')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('name'));
 echo $this->formRow($form->get('address'));
 echo $this->formRow($form->get('phone'));
 echo $this->formRow($form->get('dob'));
 echo $this->formRow($form->get('image'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();